### ISSUE TITLE
I just added an [example of multi-agent orchestration](https://github.com/huggingface/smolagents/blob/main/docs/source/examples/multiagents.md) @MonolithFoundation @whisper-bye!

### ISSUE THREAD

**Issue by shivam13297** [huggingface/smolagents#14]
I just added an [example of multi-agent orchestration](https://github.com/huggingface/smolagents/blob/main/docs/source/examples/multiagents.md) @MonolithFoundation @whisper-bye!
Tell me what you think!

_Originally posted by @aymeric-roucher in https://github.com/huggingface/smolagents/issues/3#issuecomment-2566327823_

I could not find it, it gives a 404 error

**Comment by aymeric-roucher** [comment]
The link has been updated to [https://github.com/huggingface/smolagents/blob/main/docs/source/en/examples/multiagents.md](https://github.com/huggingface/smolagents/blob/main/docs/source/en/examples/multiagents.md)
