### ISSUE TITLE
Python function as a tool

### ISSUE THREAD

**Issue by shivam13297** [huggingface/smolagents#15]
If I create a python function to do a particular task, can I use that python function as a tool? If so how? I created a python function that creates a dataframe of information that I want to pass it in as a tool, I tried that but I'm getting a attribute error

AttributeError                            Traceback (most recent call last)
[<ipython-input-20-349bcbef1fc9>](https://localhost:8080/#) in <cell line: 62>()
     60 
     61 # Create and run agent
---> 62 agent = CodeAgent(tools=[fetch_database_schema_tool], model=HfApiModel())
[/usr/local/lib/python3.10/dist-packages/smolagents/tools.py](https://localhost:8080/#) in <dictcomp>(.0)
    955 
    956     def __init__(self, tools: List[Tool], add_base_tools: bool = False):
--> 957         self._tools = {tool.name: tool for tool in tools}
    958         if add_base_tools:
    959             self.add_base_tools()

Is there a list of tools or some fixed number of tools I can use or is there a way I can do this?

**Comment by haesleinhuepf** [comment]
Hi @shivam13297 ,

have you tried decorating your function with `@tool` as demonstrated in [this example](https://github.com/huggingface/smolagents/blob/696d147020d544df2ed30290de340b97c4a2bf40/examples/tool_calling_agent_from_any_llm.py#L12)?

Best,
Robert

**Comment by shivam13297** [comment]
It worked thank you
