### ISSUE TITLE
Can't use local model using Ollama in the tool_calling_agent_ollama.py example

### ISSUE THREAD

**Issue by bilawalriaz** [huggingface/smolagents#19]
Hello, this is my first meaningful (i hope) OSS contribution.

In tool_calling_agent_ollama.py, we get the following error when trying to run:

```Traceback (most recent call last):
  File "/Users/user/coding/smolagent/agent.py", line 5, in <module>
    model = LiteLLMModel(model_id="openai/llama3.2",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LiteLLMModel.__init__() got an unexpected keyword argument 'api_base'
```

Here is the relevant code:

```
model = LiteLLMModel(model_id="openai/llama3.2",
                     api_base="http://localhost:11434/v1", # replace with remote open-ai compatible server if necessary
                     api_key="your-api-key")               # replace with API key if necessary
```

To fix it, we need to change "openai/llama3.2" to "**ollama**/llama3.2"

PR here: https://github.com/huggingface/smolagents/pull/18

**Comment by aymeric-roucher** [comment]
Indeed we'd have a problem with this model_id, I'm fixing this issue!

**Comment by aymeric-roucher** [comment]
Fixed in this commit: https://github.com/huggingface/smolagents/commit/dd1e0c50b6c46dbaa4c2843666ef483bd502c4ef
