### ISSUE TITLE
How to call OpenAI-like models through an API?

### ISSUE THREAD

**Issue by win4r** [huggingface/smolagents#2]
How to call OpenAI-like models through an API?

**Comment by holazzer** [comment]
You can use the `LiteLLMModel` which is a wrapper using `litellm`.

**Comment by aymeric-roucher** [comment]
Hellow @win4r!

You can use our LiteLLM integration and just specify the `model_id` of your model:
```py
from smolagents import LiteLLMModel
model = LiteLLMModel(model_id="gpt-4o")
```

Then just start an agent with this:
```py
from smolagents import CodeAgent

agent = CodeAgent(tools=[], model=model)

agent.run("What's the 20th number in the Fibonacci sequence?")
```
