### ISSUE TITLE
Provide more agents examples

### ISSUE THREAD

**Issue by MonolithFoundation** [huggingface/smolagents#3]
Currently, everyone is talking about agents. However, most only offer examples like "search today's temperature". While this is not entirely useless, it is not overly useful either. Some more general and advanced agent examples would be more convincing.

**Comment by aymeric-roucher** [comment]
@MonolithFoundation, that's a good point!
I was precisely searching for some examples: do you have some ideas of stuff that would have a real "wow effect" ?

**Comment by MonolithFoundation** [comment]
Yes. If individuals possess passion and time, the following suggestions come to mind. These suggestions are not only entertaining but also useful:

- Compose image and text-rich articles based on a given title or several provided materials. This implies that agents need to comprehend and analyze the title, utilize search engines to gather materials, and assemble an article interspersed with images and text that is ready for publication. (Initially, there is no need to understand images, but one must know how to insert images in the correct positions within the article. Additionally, the article should not appear to be generated by AI.)
- Computer control Agents (high level and need multi-modal abilities);

The primary objective of this proposal is not to confine AI agents to revealing text information but to expand to a more diverse range and make it possible for the output to be publishable and easily digested by users.

**Comment by whisper-bye** [comment]
Could you provide an example of multi-agent orchestration? It would be helpful to see how to coordinate multiple agents within the framework.

**Comment by Emasoft** [comment]
Please provide examples of multi-agents orchestration.

**Comment by aymeric-roucher** [comment]
I just added an [example of multi-agent orchestration](https://github.com/huggingface/smolagents/blob/main/docs/source/examples/multiagents.md) @MonolithFoundation !
Tell me what you think!

**Comment by MonolithFoundation** [comment]
Please add article writter

**Comment by aymeric-roucher** [comment]
I think it's good as is for now! I'll come back to it if there's need to demonstrate a specific technical difficulty.
