### ISSUE TITLE
broken link 

### ISSUE THREAD

**Issue by stebansaa** [huggingface/smolagents#6]
readme broken link here:

Head to [our high-level intro to agents](https://huggingface.co/docs/smolagents/conceptual_guides/intro_agents) to learn more on that.

**Comment by onuralpszr** [comment]
Hello, I hit the same issue and I think HF will connect this repo for update docs as well and for the link:

https://github.com/huggingface/smolagents/tree/main/docs/source/conceptual_guides 

I hope that helps.

**Comment by musaspacecadet** [comment]
> readme broken link here:
> 
> Head to [our high-level intro to agents](https://huggingface.co/docs/smolagents/conceptual_guides/intro_agents) to learn more on that.

also broken lol

**Comment by aymeric-roucher** [comment]
Hello all! Thank you for raising this: the issue has just been fixed as I've put our documentation pages online!
